### PR TITLE
Feature/paste with padding

### PR DESCRIPTION
**Pull request by morloy**
Extension of #55 that allows the table to grow vertically if more content is pasted.

### CODE REVIEW

**Comment by iddan** [comment]
Thank you for your contribution! I'm quite busy right now but I'll try to get around reviewing this soon.

**Comment by iddan** [comment]
Will review once #55 is merged.

**Comment by iddan** [comment]
Please resolve conflicts for review

**Comment by iddan** [comment]
Thank you!

**Comment by morloy** [comment]
@iddan would you mind releasing a new version with the new features?

**Comment by iddan** [comment]
Will do

**Comment by iddan** [comment]
Published react-spreadsheet@0.4.44

**Comment by morloy** [comment]
Thanks!

**Pull request merged**
