### PR TITLE
Fix data editor width

### LINKED ISSUE #224: Auto resizing edit cell
Hi @iddan,

after #221 the cell automatically updates the Dimension but after writing some text the input is still a bit off on the left side.
I think that can be fixed if we change the width of the dataEditor input from 98% to 100%. (Why is it even 98% and not 100% ?)

image

### PR DESCRIPTION
**Pull request by jerebtw**
Fixes #224

### CODE REVIEW

**Comment by iddan** [comment]
Thank you for the contribution @jerebtw. Can you please provide a screenshot with the effect of the change please?

**Comment by iddan** [comment]
Sorry, just noticed you added a screenshot in the issue.

**Comment by jerebtw** [comment]
> Sorry, just noticed you added a screenshot in the issue.

Yes and this PR removes that problem from the screenshot.

**Comment by iddan** [comment]
Released in react-spreadsheet@0.7.2

**Pull request merged**
