### PR TITLE
adds ability to manually select cells

### PR DESCRIPTION
**Pull request by joshualcoffee**
At the moment there is no way to manually select cells.  This functionality would be great to select full columns.  
If you are interested in this change I'll be happy to help write a few test for the actions and Provider.

### CODE REVIEW

**Comment by iddan** [comment]
Yes please do

**Comment by iddan** [comment]
Can you please provide the tests?

**Comment by iddan** [comment]
?

**Comment by joshualcoffee** [comment]
@iddan sorry, im going to close this for the time being.  The company i'm doing this for is not using this at the moment and I dont have the time to update test at the moment :-/

**Comment by iddan** [comment]
Okay, thanks for the update @joshualcoffee

**Pull request closed without merging**
