### PR TITLE
Support pasting 1 cell to multiple cells

### LINKED ISSUE #109: Paste single cell value into multiple cells
Hey @iddan 👋

Any idea how difficult it would be to allow a single cell value to be copied and then pasted into multiple (highlighted) cells? 

For example:
1. Copy a single cell
2. Highlight a range of cells
3. Paste
4. Have the single cell value pasted into each highlighted cell 

<div display="flex">
Screen Shot 2564-02-26 at 17 19 52
Screen Shot 2564-02-26 at 17 20 03
</div>

If you don't see any immediate issues with implementing this, I will give it a try myself and raise a PR. I guess that this would be a good place for me to start? https://github.com/iddan/react-spreadsheet/blob/master/src/actions.ts#L138

### PR DESCRIPTION
**Pull request by jxu10**
Resolves #109

### CODE REVIEW

**Comment by iddan** [comment]
Amazing

**Comment by Lucas-Bezerra-Santos** [comment]
Amazing!!!

It is feature  disponible to use in current version?
@iddan

**Comment by iddan** [comment]
Yes, I'm working on cutting the new version

**Comment by iddan** [comment]
Available in react-spreadsheet@0.8.4

**Pull request merged**
